actors:
  gashy:
    image_url: /images/actors/gashy.png
    name: がっしー
    url: https://www.facebook.com/fumiko10
  masaway:
    image_url: /images/actors/masae.png
    name: うぇい
    url: https://twitter.com/ysak0824
  takeshi:
    image_url: /images/actors/takeshi.jpg
    name: たけし
    url: https://twitter.com/_takeshi_24
  jon:
    image_url: /images/actors/jon.jpg
    name: ジョン
  tsuru:
    image_url: /images/actors/turusan.jpg
    name: つるさん
  norichan:
    image_url: /images/actors/norichan.jpg
    name: のりちゃん
  abalol:
    image_url: /images/actors/abalol.jpg
    name: あばろ
  taikun:
    image_url: /images/actors/taikun.jpg
    name: たいくん
  atsushi:
    image_url: /images/actors/atsushi.jpg
    name: あつしさん
  kosuke:
    image_url: /images/actors/kosuke.jpg
    name: こうすけさん
  yasu:
    image_url: /images/actors/yasu.jpg
    name: やすくん
  ru:
    image_url: /images/actors/ru.jpg
    name: るーちゃん
  kei:
    image_url: /images/actors/kei.jpg
    name: けいくん
  kensei:
    image_url: /images/actors/kensei.jpg
    name: けんせいさん
  hayato:
    image_url: /images/actors/hayato.jpg
    name: はやとさん


author: diffeasy
description: diffeasyの中の人がお届けするPodcastです！
description_long: diffeasyの中の人がお届けするPodcastです！diffeasy内で起きた出来事を様々なメンバーの目線でお届けします！
email: info@diffeasy.com  
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: diffeasy
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Inside of diffeasy
url: https://diffeasy.github.io/inside-of-diffeasy/
