actors:
  alice:
    image_url: /images/actors/alice.png
    name: alice
    url: http://sns.example.com/alice
  bob:
    image_url: /images/actors/bob.png
    name: bob
    url: http://sns.example.com/bob
author: diffeasy
description: diffeasyの中の人がお届けするPodcastです！
description_long: diffeasyの中の人がお届けするPodcastです！diffeasy内で起きた出来事を様々なメンバーの目線でお届けします！
email: info@diffeasy.com  
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: diffeasy
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Example title
url: http://example.com
